from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.units import inch

OUT='cv.pdf'
INK=colors.HexColor('#0A2F33'); TEAL=colors.HexColor('#0D7778'); MUTED=colors.HexColor('#536866'); AQUA=colors.HexColor('#91D9D5')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='CVTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=24, leading=26, textColor=INK, alignment=TA_LEFT, spaceAfter=2))
styles.add(ParagraphStyle(name='Role', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=11.5, leading=14, textColor=INK, spaceAfter=3))
styles.add(ParagraphStyle(name='Body9', parent=styles['Normal'], fontName='Helvetica', fontSize=9.2, leading=12.1, textColor=colors.black, spaceAfter=3))
styles.add(ParagraphStyle(name='Small', parent=styles['Normal'], fontName='Helvetica', fontSize=8.4, leading=10.8, textColor=colors.black, spaceAfter=1.5))
styles.add(ParagraphStyle(name='H1x', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=12.5, leading=14, textColor=TEAL, spaceBefore=8, spaceAfter=4))
styles.add(ParagraphStyle(name='BulletX', parent=styles['Body9'], leftIndent=10, firstLineIndent=-7, bulletIndent=0, spaceAfter=1.6))

def link(label,url): return f'<link href="{url}" color="#0D7778"><u>{label}</u></link>'
def P(text,style='Body9'): return Paragraph(text,styles[style])
def bullet(text): return Paragraph('• '+text,styles['BulletX'])

def footer(canvas,doc):
    canvas.saveState(); canvas.setStrokeColor(AQUA); canvas.setLineWidth(.5); canvas.line(doc.leftMargin,0.48*inch,letter[0]-doc.rightMargin,0.48*inch)
    canvas.setFillColor(MUTED); canvas.setFont('Helvetica',7.8); canvas.drawCentredString(letter[0]/2,0.30*inch,'Dr. Ahmed Ayoub - Public Academic CV - 2026'); canvas.restoreState()

story=[P('Dr. Ahmed Ayoub','CVTitle'),P('Assistant Professor of Computer Engineering','Role'),P('Department of Computer Systems Engineering, Faculty of Engineering, MSA University, Egypt')]
story.append(P(f'<b>Email:</b> {link("aelsayedo@msa.edu.eg","mailto:aelsayedo@msa.edu.eg")} &nbsp;&nbsp; | &nbsp;&nbsp; <b>ORCID:</b> {link("0009-0004-7895-3191","https://orcid.org/0009-0004-7895-3191")} &nbsp;&nbsp; | &nbsp;&nbsp; {link("Google Scholar","https://scholar.google.com/citations?user=xIUPsc8AAAAJ&hl=en")} &nbsp;&nbsp; | &nbsp;&nbsp; {link("LinkedIn","https://www.linkedin.com/in/dr-ahmed-ayoub")} &nbsp;&nbsp; | &nbsp;&nbsp; {link("Portfolio","https://aayoubmsa.github.io/ahmed-ayoub-portfolio/")}','Small'))
story += [Spacer(1,4),Table([['']],colWidths=[7.0*inch],rowHeights=[1],style=[('BACKGROUND',(0,0),(-1,-1),AQUA)]),P('PROFILE','H1x'),P('Assistant Professor of Computer Engineering with academic and research experience across Egypt, Saudi Arabia, and Hungary. Work spans applied AI, intelligent sensing, embedded systems and IoT, cyber-physical systems, computer vision, digital image processing, and engineering education. Emphasis is placed on system architecture, realistic implementation constraints, and experimental validation appropriate to the claim being made.'),P('RESEARCH AREAS','H1x')]
areas=[('<b><font color="#0D7778">Intelligent Sensing</font></b><br/>Sensor credibility, multimodal sensing, state estimation'),('<b><font color="#0D7778">Embedded &amp; Edge AI</font></b><br/>Resource-aware inference, resilient edge-to-cloud systems'),('<b><font color="#0D7778">IoT &amp; Cyber-Physical Systems</font></b><br/>Connected monitoring, control, and field deployment'),('<b><font color="#0D7778">Computer Vision</font></b><br/>Detection, localization, event understanding'),('<b><font color="#0D7778">Digital Imaging &amp; Optical Computing</font></b><br/>Image processing, holography, optical computing'),('<b><font color="#0D7778">Engineering Education</font></b><br/>Student research, curriculum and laboratory development')]
t=Table([[P(areas[0],'Small'),P(areas[1],'Small'),P(areas[2],'Small')],[P(areas[3],'Small'),P(areas[4],'Small'),P(areas[5],'Small')]],colWidths=[2.31*inch]*3,hAlign='LEFT'); t.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),2),('BOTTOMPADDING',(0,0),(-1,-1),3)])); story.append(t)
story.append(P('ACADEMIC &amp; RESEARCH APPOINTMENTS','H1x'))
for x in ['<b>2019-Present</b> &nbsp; Assistant Professor, Computer Engineering - MSA University, Egypt','<b>2012-2019</b> &nbsp; Assistant Professor, Computer Science - University of Tabuk, Saudi Arabia','<b>2010-2013</b> &nbsp; Postdoctoral Research - University of Debrecen, Hungary','<b>2009-2012</b> &nbsp; Chairman, Computer Science Department - Shaqra University, Saudi Arabia','<b>2000-2008</b> &nbsp; Research Engineer / Senior Research Engineer - SZTAKI, Budapest, Hungary']: story.append(P(x,'Small'))
story.append(P('EDUCATION','H1x'))
for x in ['PhD in Optical Computing - Budapest University of Technology and Economics, Hungary, 2005','MSc in Biophysics Engineering - Cairo University, Egypt, 2000','BSc in Physics - Zagazig University, Egypt, 1997','BSc in Computer Engineering (Honors) - Benha University, Egypt, 1994']: story.append(bullet(x))
story.append(P('TEACHING &amp; ACADEMIC SERVICE','H1x'))
for x in ['Teaching areas include Software Engineering, Database Systems, Operating Systems, Programming, Algorithms, Computer Architecture, Digital Logic, Digital Image Processing, Computer Vision, and Information Retrieval.','Supervises graduation projects and student research in applied AI, computer vision, intelligent sensing, embedded systems, and cyber-physical applications.','Contributes to course specification, outcome alignment, curriculum development, programme assessment, laboratory development, moderation, and continuous-improvement activities.']: story.append(bullet(x))
story += [PageBreak(),P('SELECTED PUBLICATIONS','H1x')]
pubs=[('2026','A. T. Mohamed, S. K. Shalaby, and A. Ayoub, “Hierarchical Fit-Valid Allocation for Multi-Class Dimension-Aware Smart Parking Systems,” <i>MSA Engineering Journal</i>, 2026.',link('DOI','https://doi.org/10.21608/msaeng.2026.494220.1441')),('2025','M. Othman and A. Ayoub, “FireModelAI: A Smart Framework for Fire Detection, Localization, and Classification Indoors,” in <i>2025 Intelligent Methods, Systems, and Applications (IMSA)</i>, pp. 208-213, 2025.',link('DOI','https://doi.org/10.1109/IMSA65733.2025.11167718')),('2015','Y. Abdelhamid, A. Ayoub, and M. Alhawiti, “Agent-Based Intelligent Academic Advisor System,” <i>International Journal of Advanced Computer Technology</i>, vol. 4, no. 2, pp. 1-6, 2015.',''),('2012','A. Ayoub, A. Hajdu, and A. Nagy, “Automatic Detection of Pigmented Network in Melanoma Dermoscopic Images,” <i>International Journal of Computer Science and Communication Security</i>, vol. 2, pp. 58-63, 2012.',''),('2007','A. Ayoub and S. Tokes, “Digital In-Line Holographic Microscope Algorithms for Micro-Organisms Detection and Three Dimension Tracking,” in <i>Proceedings of the Third International Computer Engineering Conference</i>, Cairo, Egypt, pp. MI8-13, 2007.',''),('2006','A. Ayoub, S. Tokes, and L. Orzo, “Optical Cellular Wave Computer Implementation and Programming,” in <i>10th International Workshop on Cellular Neural Networks and Their Applications (CNNA 2006)</i>, Istanbul, Turkey, 2006.',link('DOI','https://doi.org/10.1109/CNNA.2006.341604'))]
for y,cite,doi in pubs: story.append(P(f'<b><font color="#0D7778">{y}</font></b> &nbsp; {cite} {doi}','Small'))
story.append(P(f'<b>Complete publication record:</b> {link("Google Scholar","https://scholar.google.com/citations?user=xIUPsc8AAAAJ&hl=en")} &nbsp; | &nbsp; {link("ORCID","https://orcid.org/0009-0004-7895-3191")} &nbsp; | &nbsp; {link("IEEE Xplore","https://ieeexplore.ieee.org/author/436556479741036")}','Small'))
story.append(P('SELECTED RESEARCH EVIDENCE','H1x'))
for label,desc,url in [('FireModelAI','Indoor fire detection, localization and classification. The study reports 88.46% detection accuracy and 1.26 cm mean localization error under its experimental conditions.','https://aayoubmsa.github.io/ahmed-ayoub-portfolio/firemodelai.html'),('Fit-Valid Smart Parking','Dimension-aware allocation evaluated through simulation and an ESP32/ultrasonic prototype.','https://aayoubmsa.github.io/ahmed-ayoub-portfolio/smart-parking.html'),('Digital Holographic Microscopy','Digital reconstruction, biological micro-organism detection and three-dimensional tracking from in-line holograms.','https://aayoubmsa.github.io/ahmed-ayoub-portfolio/digital-holography.html')]: story.append(P(f'{link(label,url)} - {desc}'))
story.append(P('SELECTED AWARDS','H1x'))
for x in ['Best Paper Award - Third International Computer Engineering Conference (ICENCO), Egypt, 2007','Best Doctoral Research Prize - Hungarian Academy of Sciences, 2003','CNN Young Researcher Award - IEEE CNNA, 2002']: story.append(bullet(x))
story += [P('COLLABORATION','H1x'),P('Open to research collaboration, funded multidisciplinary projects, applied R&amp;D, technical work-package ownership, prototype evaluation, and research-oriented student projects in intelligent sensing, embedded systems, IoT, computer vision, and engineering validation.'),P(f'{link("Portfolio","https://aayoubmsa.github.io/ahmed-ayoub-portfolio/")} &nbsp; | &nbsp; {link("Contact by email","mailto:aelsayedo@msa.edu.eg")}')]
doc=SimpleDocTemplate(OUT,pagesize=letter,rightMargin=.62*inch,leftMargin=.62*inch,topMargin=.52*inch,bottomMargin=.60*inch,title='Dr. Ahmed Ayoub - Public Academic CV 2026',author='Dr. Ahmed Ayoub',subject='Public academic CV')
doc.build(story,onFirstPage=footer,onLaterPages=footer)
